services:
  db:
    container_name: mysql
    build: .
    restart: always
    # m1mac用にplatformを指定
    platform: linux/amd64
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    privileged: true
    networks:
      - common-network
networks:
  common-network:
    external: true
